apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "3002"
  NODE_ENV: "development"
  JWT_EXPIRES_IN: "1h"
  LOG_LEVEL: "debug"
  KAFKA_BROKERS: "event-cluster-kafka-bootstrap.kafka:9092"