apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:   # First Spec defines how to manage the application
  replicas: 1
  selector:
    matchLabels:
      app: payment-service  # what Pods should this deployment manage
  template:              #K8 looks at this whenever a new pod if to be created
    metadata:
      labels:
        app: payment-service  #Every Pod created by this deployment gets this sticker
    spec:
      containers:
      - name: payment-service
        image: skymonil/payment-service:latest  # ðŸ”´ CHANGE THIS to your actual image
        envFrom:
        - configMapRef:
            name: payment-service-config
        - secretRef:
            name: payment-service-secrets
        ports:
        - containerPort: 3002