apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment-service  # Label to identify the Service
spec:
  # ðŸŸ¢ type: LoadBalancer tells MetalLB to give this an External IP
  type: LoadBalancer 
  selector:
    app: payment-service # It tells the Service where to send the traffic.
  ports:
    - name: http
      port: 3002       # The port you'll use in your browser/Postman
      targetPort: 3002 # The port your Node.js app is listening on
      protocol: TCP