apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: default
  labels:
    app: inventory-service  # Label to identify the Service
spec:
  # ðŸŸ¢ type: LoadBalancer tells MetalLB to give this an External IP
  type: LoadBalancer 
  selector:
    app: inventory-service # It tells the Service where to send the traffic.
  ports:
    - name: http
      port: 3003       # The port you'll use in your browser/Postman
      targetPort: 3003 # The port your Node.js app is listening on
      protocol: TCP