apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml        # Assumes you have a folder for prometheus
  - jaeger.yaml     # Assumes you have a folder for grafana
  - analysis/          # ðŸŸ¢ Explicitly include the analysis folder
  - argocd-otel.yaml