apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - http-golden-signals.yaml
  # - http-smoke-test.yaml      <-- Add this if you created it earlier
  # - kafka-consumer-health.yaml <-- Add this if you created it earlier