apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- digest: sha256:610160686793a4fa6215525b1dfe4bb0e7516dabb7944b5353c87a0a0b04d06d
  name: skymonil/user-service
  newName: skymonil/user-service
