apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- digest: sha256:1bb18d0a0d98e2823e8b11f1ef57312ad2cf39a42fb2a72effaa79b30e597d22
  name: skymonil/user-service
  newName: skymonil/user-service
