apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- name: skymonil/user-service
  newName: skymonil/user-service
  newTag: afd98e265a9d5a58e8aa19ffac20f6f9865ab1a3
