apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- name: skymonil/user-service
  newName: skymonil/user-service
  newTag: 2629239e7b684929080bc0ec5f36415e8d42a818
